version: "3"
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE : 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
    web:
        build: .
        ports:
            - "8080:8080"